controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_01_controller:
      type: forward_command_controller/ForwardCommandController
      
    joint_02_controller:
      type: forward_command_controller/ForwardCommandController
      
    joint_03_controller:
      type: forward_command_controller/ForwardCommandController
      
    joint_04_controller:
      type: forward_command_controller/ForwardCommandController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
      
      
joint_01_controller:
  ros__parameters:
    joints:
      - arm_joint_01
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      
joint_02_controller:
  ros__parameters:
    joints:
      - arm_joint_02
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      
joint_03_controller:
  ros__parameters:
    joints:
      - arm_joint_03
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      
joint_04_controller:
  ros__parameters:
    joints:
      - arm_joint_04
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
